# !! THIS FILE HAS BEEN GENERATED BY convert_markdown.py SCRIPT.
# !! DO NOT MODIFY MANUALLY EXCEPT FOR VERY QUICK TESTING,
# !! AS ANY CHANGES WILL BE OVERWRITTEN ON NEXT CONVERSION FROM MARKDOWN SOURCES

## %% Boy has just received paper result and is angry at the imperfect grade: 120 %%
### %% White screen: teacher distributes papers to students, saying grades out loud %%
label scene1:

    # show white BG
    t "Thomas, 15."

    "The boy stands up and comes to my desk to receive his corrected paper, seemingly satisfied."

    t "Héloïse, 13."

    "The girl tries hard to hide her pout as she takes the essay, but I can see through. I know she's used to better. It's a pity, but her depiction of Russia's stance on decolonisation was more than inaccurate."

    t "Ismail, 16."

    "The procession continues for a minute."

    t "Đạt, 17."

    "I don't know this one, he wasn't in my class last year. 17 out of 20 is very good, but the pupil doesn't show the hint of a smile. Either it's his usual grade, or he {i}is{/i} the king of poker faces."

    t "Jordan, 19."

    "Jordan, with his usual enjoyed gait, comes to receive his trophy. As he comes back to his seat, his friends are tapping him on the back."

    "I finish giving the papers back and address the class:"

    t "That's it, I'll give you some time to check your answers once more. Tell me if you have any questions."

    ### %% we hear boy crumpling paper %%
    # SFX: crumpling paper
    "I hear some paper being crumpled."

    "I look around and see Đạt clutching his essay, firmly wrapped into a paper ball."

    "He's staring at the bin standing in a corner of the classroom, but instead of throwing the ball, he unwraps it and tries to flatten it down on his desk – maybe to check his answers once more, as instructed."

    "But he doesn't have much to correct, so he just stays there glaring at his essay."

    ### %% Scene shows boy’s desktop and half-crumpled paper %%
    # Scene: show boy's desktop + half-crumpled paper + boy's bust
    ## %% Other pupils around murmur and complain about his behaviour, but the boy ignores them: 40 %%
    "Some of the other students glance at him, but quickly feel uncomfortable and look away."

    "I suppose most of them have lower grades and don't appreciate seeing a peer complaining while faring better."

    ## %% New teacher approaches boy who can do nothing but be annoyed, and starts discussing: 30 %%
    "I'd better have a look to find out what's wrong. I walk to his desk."

    ## %% They talk about the optimistic and pessimistic view on grades: 80 %%
    ### %% Teacher says A- (or some equivalent like 17/20) is a very good grade %%
    menu:

        "How should I start the conversation?"

        "Compliment him on his writing":

            jump .good_job

        "Ask him why he crumpled the paper":

            jump .why_crumple

label .good_job:

    t "Good job! The part on the Third World's non-alignment with the United States and the USSR was well constructed."

    "Đạt raises his eyes to look at me, but my compliment only makes him grimace."

    b "If it was only about that…"

    jump .flip_pages

label .why_crumple:

    t "Why did you crumple your essay? It was very good."

    b "Not good enough, apparently."

    jump .flip_pages

label .flip_pages:

    "He flips the pages to focus on other parts of the test, revealing a few other points I had marked in red while correcting the paper."

    t "Yes, the dates were not really accurate, but what matters is that you got the big picture."

    ### %% Pupil says then why the minus / that 17 is 3 points away from 20. Three stupid mistakes. Being the first in the class would make it acceptable, but it's not even the case. %%
    "The boy frowns."

    b "It's not just the dates, I also got the events wrong, and it was obvious from a logical standpoint."

    t "Maybe, but the rest was correct, enough to be worth 17 points in my grading."

    b "To me, it's just 3 points missing. And I could have avoided that, the other pupils prove it."

    # => unlock rivalry talk
    ## %% They talk about alternative ways to score and deliver score to pupils (self-correction, no grade, no public grade announcement…): 120 %%
    ### %% Maybe ABC would be better than numeric score? %%
label alternative_grading:

    t "Maybe the 20-point grading system makes you feel that way because it's so precise? What if I was using some A-B-C-D grading?"

    b "… well it'd probably feel like covering my mistakes, but at least I'd have the satisfaction of being top-ranked, even with a few mistakes – assuming I get A. Wouldn't 17 be more like a B though?"

    t "Hm… I suppose so. But more likely a B+!"

    b "…"

    ### %% They talk about how the broad skill matters more than the details. After all, this is how it looks like in a pro environment, where there are no grades %%
    t "Anyway, my point is, you have to focus on the big picture: the test ensures that you have a broad understanding of the topic."

    t "Then, if you couldn't answer some questions, that's something you can dig deeper."

    b "But I already see what was wrong, and I have nothing more to learn."

    t "Then that's great too. Most students here don't understand what is missing, and have difficulties fixing their shortcomings. Being able to understand one's mistakes quickly is a quality."

    b "…"

    t "And sometimes, even then, it's worth digging deeper: the test, after all, can be succeeded by tackling the surface of each topic, but real history is much deeper."

    t "The more you understand a topic in depth, the less you're likely to make small mistakes."

    t "This is what professionals and experts do: they study beyond what's asked from them."

    t "Academics don't undergo tests like these, instead they focus on researching further, writing papers or delivering talks."

    t "And office employees don't have grades either, only their overall performance matters."

    b "Hm. Sounds nice."

    ### %% T: maybe not announce grades publicly? %%
label private_grades:

    t "What about not announcing grades publicly, so you don't compare yourself to others?"

    b "I see, that would allow me to focus on my own work… Although it would feel like hiding the truth to make me feel better."

    t "You're hard on yourself!"

    ## %% They talk about working hard to survive vs chill work in a room, battlefield vs playground, education and tests vs actual work to produce something: 150 %%
    ### %% T: Why this elitism? %%
label elitism:

    t "Why do you think you need to be that much successful everywhere?"

    b "Not everywhere. Where I already know I'm not totally bad."

    t "Are your parents pushing that far?"

    b "No, I just don't like failing. Although my father appreciates it when I get good grades."

    t "I'm guessing from your name that he comes from Viêtnam?"

    b "Yes, why?"

    t "As a migrant, he may make a point of ensuring you are successful in academics in order to be both well integrated in society and make a lot of money. I am one myself so I know that feeling."

    t "But your generation lives in peace and is already well integrated. You don't need to strain yourself like this."

    b "…"

    b "But I want to deserve my parents' wealth. If I don't work in an office, studying is the second best thing I can do."

    t "I see. But in offices, employees have no grades, their overall performance and teamwork matters more."

    # TODO: combine with similar professional talk above
    ## %% They talk about self-satisfaction and using true skills to actually produce something in life and how finding this extra-curricular activity until having an actual job matters: 80 %%
    ### %% T: what do you wanna do in life? %%
    #### %% B: (nice if player choice, but then player controls everyone) %%
        #### %% video making %%

        #### %% website %%

        #### %% model %%

        #### %% dance choreography %%

    ## %% They talk about rivalry and other classmates doing better, or worse, and their own circumstances, serious training and pressure: 120 %%
    ### %% Teacher choice: Not everyone can get grades that good, you should consider yourself lucky. It annoys other pupils that you're so unsatisfied. %%
    ### %% B: and so what? It's not like they care that much. They have been used to mediocrity for a long time. Plus it's not like they work as seriously as I do. It's normal I have more expectations. %%
    ### %% Teacher choice: Is it because other pupils did better? %%
    ### %% Boy: yes, but it’s more that they proved that it was possible for a human to do so, raising the ceiling %%
    ### %% T: every human has circumstances %%
    #### %% B: but no particular handicap or difficulty, or difficult context at home %%
    ### %% T: and training %%
    #### %% B: I do all the exercices %%
    #### %% T: and more? %%
    #### %% B: no, never more %%
    #### %% T: try it %%
    #### %% B: oh… but what if my rival doesn’t, then I must work harder than them that’s unfair %%
    #### %% T: hm… maybe other pupils think the same of you. we don’t know if rival doesn’t also do extra work %%
    #### %% B: hmpf, they don’t look pressured or anything. Plus some rival always parties. %%
    #### %% T: nor do you, always talking about games. It may not be visible to the eyes. Maybe they party precisely to evacuate that stress %%
    ## %% The conversation ends, the teacher understanding better and pupil considering the teacher’s words: 50 %%
    ## %% Epilogue: 50 %%
    ### %% the boy is now is high school working on some personal project (what they said they liked answering T question) %%
    ### %% B is happy to be part of a complementary team and using unique skills %%
    ### %% B is happy to deliver a product only whose subjective quality (but assessed by an audience of young people like him) matters %%
