# !! THIS FILE HAS BEEN GENERATED BY convert_markdown.py SCRIPT.
# !! DO NOT MODIFY MANUALLY EXCEPT FOR VERY QUICK TESTING,
# !! AS ANY CHANGES WILL BE OVERWRITTEN ON NEXT CONVERSION FROM MARKDOWN SOURCES

## %% Teacher distributes paper: 100 %%
label scene1:

    scene bg white

    t "Thomas, 15."

    "The boy stands up and comes to my desk to receive his corrected paper, seemingly satisfied."

    t "Héloïse, 13."

    "The girl tries hard to hide her pout as she takes the essay, but I can see through. I know she's used to better. It's a pity, but her depiction of Russia's stance on decolonisation was more than inaccurate."

    t "Ismail, 16."

    "The procession continues for half a minute."

    t "Đạt, 17."

    "17 out of 20 is an excellent grade, but instead of a smile, the pupil lets out a sigh."

    t "Jordan, 19."

    "Jordan, with his usual joyful gait, comes to receive his trophy. He walks back to his seat under the congratulations—in teen slang—of his comrades."

    "I finish giving the papers back and address the class:"

    t "That's it. I'll give you some time to check your answers once more. Tell me if you have any questions."

    ## %% Boy crumples paper: 20 %%
label boy_crumples_paper:

    # SFX: crumpling paper
    play audio sfx.crumple_paper

    "I sort my notes to prepare the incoming lesson, when the sound of a crumpling paper catches my attention."

    "I see Đạt clutching a paper ball, even more serious than before."

    # SFX: crumpling paper
    play audio sfx.crumple_paper_short

    "I expect him to throw the ball into the bin, but instead, he unwraps it and flattens it down on his desk—revealing his wrinkled essay."

    # Scene: show boy's desktop + half-crumpled paper + boy's bust
    scene bg classroom

    "Some teenagers whisper to their neighbours while peeking at him."

    "I'd better have a look to find out what's wrong."

    "I walk to his desk."

    ## %% Teacher starts talking about the optimistic and pessimistic view on grades: 150 %%
label dialogue_start:

    menu:

        "How should I start the conversation?"

        "Pretend not to have seen anything and compliment him on his writing":

            jump good_job

        "Ask him why he crumpled the paper":

            jump why_crumple

label good_job:

    t "Good job! The part on the Third World's non-alignment with the United States and the USSR was well constructed."

    "Đạt raises his eyes to look at me, but my compliment only makes him grimace."

    b "If it was only about that…"

    jump flip_pages

label why_crumple:

    t "Why did you crumple your essay? It was very good."

    b "Not good enough, apparently."

    jump flip_pages

label flip_pages:

    "He flips the pages to focus on other parts of the test, revealing a few other points I had marked in red while correcting the paper."

    t "Yes, the dates were not really accurate, but what matters is that you got the big picture."

    "The boy frowns."

    b "It's not just the dates, I also got the events wrong. It was obvious."

    t "Maybe, but the rest was correct, enough to be worth 17 points in my grading."

    b "To me, it's just 3 points missing. And I could have avoided that. The other pupils prove it."

    ## %% HUB: Teacher can choose next topic freely: 50 %%
label dialogue_hub:

label question_grading:

    while True:

        menu:

            "So the precise scoring is what bothers you?" if not talked_about_alternative_grading:

                call alternative_grading

            "So it's because of other pupils doing better that you're not satisfied?" if not talked_about_other_classmates_better:

                call other_classmates_better

            "Everyone has their own circumstances and affinities." if unlocked_talked_about_circumstances and not talked_about_circumstances:

                call circumstances

            "Maybe I shouldn't say the grades out loud then?" if not talked_about_private_grades and unlocked_private_grades:

                call private_grades

            "Why do you need to be that successful?" if not talked_about_elitism and unlocked_elitism:

                call elitism

            "Why do you study?" if not talked_about_why_study and unlocked_why_study:

                call why_study

            #"Why don't you smile?" if not talked_about_facial_expression:

                #call facial_expression

            "That's all I wanted to say (end conversation)":

                jump dialogue_end

    ## %% They talk about alternative grading: 120 %%
label alternative_grading:

    $ talked_about_alternative_grading = True

    t "So the precise scoring is what bothers you? What about some letter grades instead? A to D?"

    b "I admit it would cover up the small mistakes… Wouldn't 17 be a B though?"

    t "Maybe… But more likely a B+!"

    b "…"

    return

    ## %% They talk about other classmates doing better, and their own circumstances: 180 %%
label other_classmates_better:

    $ talked_about_other_classmates_better = True

    t "So it's because of other pupils doing better that you're not satisfied?"

    b "Partly. They are mostly showing that it was possible to answer some questions at our level."

    $ unlocked_private_grades = True

    $ unlocked_talked_about_circumstances = True

    return

    ## %% They talk about other classmates doing better or worse, and their own circumstances: 180 %%
label circumstances:

    $ talked_about_circumstances = True

    t "Well, everyone has different circumstances, some may fare better or worse depending on their context and mental state."

    b "But I didn't have particular issues for this exam, nor in general in life. So I have no excuses."

    t "Maybe Jordan just trained a lot."

    b "I also do! I do all the homework."

    t "Maybe you can do more?"

    b "But I already see what was wrong, and I have nothing more to learn."

    t "Then that's great too. Most pupils here don't understand what is missing, and have difficulties fixing their shortcomings. Being able to understand one's mistakes quickly is a strength."

    b "I suppose so… but if Jordan can get 19 without extra work, why should I? Sounds unfair to me."

    menu:

        "Training can bring stability.":

            call stability

        "Maybe that's also what other pupils think about you.":

            call sandwich

    call circumstances_end

label stability:

    t "Maybe. But more importantly, you'll practise every day and so your 17 will be a solid 17. While you can get a 19 by revising a lot before the test, and forget it later."

    "Đạt glanced at Jordan."

    b "Hm. I don't think you can score that much just with last time revisions, but I get your point."

    return

label sandwich:

    t "Maybe that's also what other pupils think about you. Not everyone can get grades that good, after all."

    b "Well, they probably don't work as hard so I'n sure they don't care as much."

    t "But maybe some of them do?"

    b "Then that's the sandwich effect."

    pause 0.5

    t "The… sandwich?"

    b "Yes, when you rank second, you're annoyed because you couldn't beat the first. {b}And{/b} the third one and everyone else below complain about you because you beat them but still complain."

    b "So you get sandwiched between them and take a double penalty."

    t "Right, I understand…"

    return

label circumstances_end:

    t "Anyway, nothing says that Jordan is not putting extra work anywhere. If not in history, it could be in mathematics or sports."

    t "So there's no shame in doing some extra, especially on something that matters to you."

    b "Fine, I will consider."

    b "In the meantime, Jordan doesn't seem pressured or anything. He always goes to parties."

    t "You don't seem stressed outside exam results either, casually talking to your friends."

    t "Maybe he parties precisely to evacuate that stress?"

    $ unlocked_elitism = True

    $ unlocked_why_study = True

    return

    ## %% They talk about private grades: 40 %%
label private_grades:

    $ talked_about_private_grades = True

    t "Maybe I shouldn't say the grades out loud then? So you don't compare yourself to others?"

    b "Yes, that would allow me to focus on my own work… Although it would feel like hiding the truth to make me feel better."

    t "You're hard on yourself!"

    $ unlocked_elitism = True

    $ unlocked_why_study = True

    return

    ## %% They talk about working hard to survive vs studying: 150 %%
label elitism:

    $ talked_about_elitism = True

    t "Why do you think you need to be that much successful everywhere?"

    b "Not everywhere. Where I already know I'm not totally bad."

    t "Are your parents pushing that far?"

    b "No, I just don't like failing. Although my father appreciates it when I get good grades."

    t "I'm guessing from your name that he comes from Vietnam?"

    b "Yes, why?"

    t "As a migrant, he may make a point of ensuring you are successful in academics in order to be both well integrated in society and make a lot of money. I am one myself so I know that feeling."

    t "But your generation lives in peace and is already well integrated. You don't need to strain yourself like this."

    b "…"

    b "But I want to deserve my parents' wealth. If I don't work in an office, studying is the second best thing I can do."

    t "I see. But in offices, employees have no grades, their overall performance and teamwork matters more."

    $ unlocked_dialogue_end = True

    return

    ## %% They talk about the real value of knowledge skills, applied outside school: 100 %%
label why_study:

    $ talked_about_why_study = True

    t "Why are you studying for?"

    "Đạt raises an eyebrow."

    b "Well, that's what school is for. We study so we become better, we can pass exams and prove that we're worth it and go on in life."

    t "No, I mean, what do you want to do in life with everything you would have learned here?"

    "The boy ponders."

    b "No clue. I suppose I could get a job in human sciences or something, but I'm not interested in research that much."

    t "Then try to focus on the big picture: see beyond the test, that is only tackling the surface of the topic, and think about what each lesson can bring you in life."

    b "Hm. I have a feeling most classes at school are theoretical, aren't they?"

    t "That's right. The core curriculum is probably a bit too broad and many lessons sound abstract for people who are not interested in the field."

    t "But for others, that knowledge will be much more important to you than it will be for another student, even if they had a better grade."

    b "Shouldn't I become the best precisely because I want it to be my main field?"

    t "That's a good reason, but you can dig each topic deeper over time. Academics write papers and give talks, and their contribution is assessed by how much they bring to the research community."

    t "While some professionals work with companies on practical applications, and are evaluated based on what they actually produce."

    t "They don't estimate the value of their works by grades, but directly from what they can make."

    b "Hm. That sounds nice."

    $ unlocked_dialogue_end = True

    return

    ## %% The conversation ends, the teacher understanding better and pupil considering the teacher’s words: 50 %%
label dialogue_end:

    t "So, you think you can be satisfied with what you did?"

    b "I don't know. At least I know what I did wrong. For the rest, I can't guarantee."

    pause 1.0

    ## %% Epilogue: 50 %%
label epilogue:

    scene bg black

    "Epilogue - 7 years later"

    "In my living room, at the end of the documentary, I recognise a name in the credits."

    "I check on LinkedIn that it's not a homonym, but it is him."

    "It looks like Đạt is investigating cross-continental migrations and tracing the stories of families who left it all in search of a better life, without war nor totalitarianism."

    "He's probably happier now, without grades and just the satisfaction of making something meaningful for the society."

    "Oh, the film is scored 85\% on Rotten Tomatoes."

    return

